authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from geekshop.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products')),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

basketapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product
from ordersapp.models import OrderItem


class BasketQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super(BasketQuerySet, self).delete(*args, **kwargs)


class Basket(models.Model):
    objects = BasketQuerySet.as_manager()

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='basket',
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )

    add_datetime = models.DateTimeField(
        verbose_name='время',
        auto_now_add=True,
    )

    @staticmethod
    def get_item(pk):
        return Basket.objects.filter(pk=pk).first()

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        items = Basket.objects.filter(user=self.user)
        totalquantity = sum(list(map(lambda x: x.quantity, items)))
        return totalquantity

    @property
    def total_cost(self):
        items = Basket.objects.filter(user=self.user)
        totalcost = sum(list(map(lambda x: x.product_cost, items)))
        return totalcost

    def save(self, *args, **kwargs):
        if self.pk:
            self.product.quantity -= self.quantity - self.__class__.get_item(self.pk).quantity
        else:
            self.product.quantity -= self.quantity
        self.product.save()
        super(self.__class__, self).save(*args, **kwargs)

basketapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from basketapp.models import Basket
from mainapp.models import Product

from django.contrib.auth.decorators import login_required

from django.template.loader import render_to_string
from django.http import JsonResponse


@login_required
def basket(request):
    title = 'корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')
    context = {
        'title': title,
        'basket_items': basket_items,
    }
    return render(request, 'basketapp/basket.html', context)


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

        context = {
            'basket_items': basket_items,
        }

        result = render_to_string('basketapp/includes/inc_basket_list.html', context)

        return JsonResponse({'result': result})

basketapp/templates/basketapp/includes/inc__basket_items.html
{% if basket_items %}
    {% for item in basket_items %}
        <div class="basket_record">
            <img src="/media/{{ item.product.image }}" alt="{{ item.product.short_desc }}">
            <span class="category_name">{{ item.product.category.name }}</span>
            <span class="product_name">{{ item.product.name }}</span>
            <span class="product_price">{{ item.product.price }}&nbsp;&#8381;</span>
            <label>
                <input class="product_quantity" type="number" name="{{ item.pk }}" min="0"
                       max="{{ item.product.quantity }}"
                       value="{{ item.quantity }}">
            </label>
            {# <span class="product_cost">{{ item.product_cost }}&nbsp;&#8381;</span>#}

            <a href="{% url 'basket:delete' item.pk %}" class="btn btn-round">
                убрать из корзины</a>
        </div>
    {% endfor %}

    <div class="basket_summary">
        В корзине {{ user.basket_total_quantity }} товаров общей стоимостью
        {{ user.basket_cost }}&nbsp;&#8381;
    </div>
{% else %}
    <h4>В корзине нет товаров</h4>
{% endif %}

<a href="{% url 'main:index' %}" class="btn btn-round">
    на главную
</a>

basketapp/templates/basketapp/includes/inc_basket_list.html
    <div class="basket_list">
        <div class="details">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Товар</th>
                <th scope="col">Количество</th>
                <th scope="col">Стоимость</th>
                <th scope="col">Удалить</th>
            </tr>
            </thead>
            <tbody>
            {% for item in basket_items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.product.name }}</td>
                    <td>
                        <input type="number" name="{{ item.pk }}" min="0" value="{{ item.quantity }}">
                    </td>
                    <td>{{ item.product.price }} &nbspруб</td>
                    <td>
                        <button class="btn btn-round">
                            <a href="{% url 'basket:remove' item.pk %}" class="">
                                удалить
                            </a>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% if basket_items %}
        <div class="basket_summary">
            В корзине {{ basket_items.0.total_quantity }} товаров общей стоимостью
            {{ basket_items.0.total_cost }} руб
        </div>
    {% endif %}
    </div>